name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch:

jobs:
  test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    env:
      USING_COVERAGE: '3.13'
    strategy:
      fail-fast: true
      matrix:
        python-version: [ "3.13" ]
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          python -m pip install -r requirements.test.txt
      - name: "Run tests for ${{ matrix.python-version }}"
        run: |
          pytest tests/ -v